# Generated by Django 5.2.6 on 2025-09-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('avatar', models.URLField()),
                ('title', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('desc', models.TextField(default='')),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.TextField(default='')),
            ],
        ),
    ]
