# Generated by Django 5.2.6 on 2025-09-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='report',
            name='location',
            field=models.CharField(default=''),
        ),
    ]
