# Generated by Django 5.2.6 on 2025-09-28 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.conf import settings


def forwards_populate_author_fk(apps, schema_editor):
    Report = apps.get_model('core', 'Report')
    User = apps.get_model('core', 'User')

    for report in Report.objects.all():
        old_author_name = getattr(report, 'author', None)
        if old_author_name is None:
            continue
        username = str(old_author_name).strip()
        if not username:
            continue
        user, _ = User.objects.get_or_create(username=username, defaults={'email': '', 'user_email': ''})
        setattr(report, 'author_fk_id', user.id)
        report.save(update_fields=['author_fk'])


def backwards_unpopulate_author_fk(apps, schema_editor):
    Report = apps.get_model('core', 'Report')
    for report in Report.objects.select_related('author_fk').all():
        user = getattr(report, 'author_fk', None)
        if user is not None:
            report.author = user.username
            report.save(update_fields=['author'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_report_category_report_image_report_location'),
    ]

    operations = [
        # 1) Add a temporary FK field
        migrations.AddField(
            model_name='report',
            name='author_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        # 2) Backfill from string author -> author_fk
        migrations.RunPython(forwards_populate_author_fk, backwards_unpopulate_author_fk),
        # 3) Drop old string field
        migrations.RemoveField(
            model_name='report',
            name='author',
        ),
        # 4) Rename temporary field to canonical name
        migrations.RenameField(
            model_name='report',
            old_name='author_fk',
            new_name='author',
        ),
        # 5) Ensure field is non-nullable going forward
        migrations.AlterField(
            model_name='report',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        # 6) Adjust image upload path as intended
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
