# Generated by Django 5.2.6 on 2025-09-16 07:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
