# Generated by Django 5.2.6 on 2025-10-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_user_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.URLField(default='images/profile.png'),
        ),
    ]
