# Generated by Django 5.2.6 on 2025-10-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.URLField(default='/static/images/profile.png'),
        ),
    ]
