# Generated by Django 5.2.6 on 2025-10-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
