# Generated by Django 5.2.6 on 2025-10-21 08:33

from django.db import migrations
import os


def fix_image_paths(apps, schema_editor):
    """
    Fix existing image paths by removing the duplicate 'media/' prefix
    """
    Report = apps.get_model('core', 'Report')
    
    for report in Report.objects.filter(image__isnull=False).exclude(image=''):
        if report.image and 'media/media/' in str(report.image):
            # Remove the duplicate 'media/' prefix
            old_path = str(report.image)
            new_path = old_path.replace('media/media/', 'media/')
            
            # Check if the file exists at the new location
            if os.path.exists(new_path):
                # Update the database field
                report.image = new_path
                report.save(update_fields=['image'])
                print(f"Fixed image path for report {report.id}: {old_path} -> {new_path}")


def reverse_fix_image_paths(apps, schema_editor):
    """
    Reverse the image path fix (add back the duplicate 'media/' prefix)
    """
    Report = apps.get_model('core', 'Report')
    
    for report in Report.objects.filter(image__isnull=False).exclude(image=''):
        if report.image and not 'media/media/' in str(report.image) and 'media/' in str(report.image):
            # Add back the duplicate 'media/' prefix
            old_path = str(report.image)
            new_path = old_path.replace('media/', 'media/media/')
            
            # Check if the file exists at the old location
            if os.path.exists(new_path):
                # Update the database field
                report.image = new_path
                report.save(update_fields=['image'])
                print(f"Reverted image path for report {report.id}: {old_path} -> {new_path}")
    

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_report_category_alter_report_location'),
    ]

    operations = [
        migrations.RunPython(fix_image_paths, reverse_fix_image_paths),
    ]
