# Generated by Django 5.2.6 on 2025-10-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20251021_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='liked',
            field=models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
