# Generated by Django 5.2.6 on 2025-10-24 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='likes',
        ),
    ]
