# Generated by Django 5.2.6 on 2025-10-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_report_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
