# Generated by Django 5.2.6 on 2025-10-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_notification_related_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='avatar',
            field=models.URLField(default='/static/images/profile.png/'),
            preserve_default=False,
        ),
    ]
