# Generated by Django 5.2.6 on 2025-10-27 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_comments_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsAndActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
