# Generated by Django 5.2.6 on 2025-10-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_eventsandactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsandactivity',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='eventsandactivity',
            name='image',
            field=models.URLField(default='/static/images/default_event.jpg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventsandactivity',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='eventsandactivity',
            name='time',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='eventsandactivity',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
