# Generated by Django 5.2.6 on 2025-10-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_eventsandactivity_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsandactivity',
            name='location',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
