# Generated by Django 5.2.6 on 2025-10-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_eventsandactivity_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsandactivity',
            name='time',
            field=models.CharField(blank=True, default='', max_length=75, null=True),
        ),
    ]
